### PR TITLE
Vrbahl fix gps parser

### PR DESCRIPTION
**Pull request by VivaanBahl**
Updated code to reflect the actual way we should parse the longitude from GPS

### CODE REVIEW

**Comment by TrevorDecker** [comment]
I feel like something is missing is it really only 

+	private double convertMinSecToFloat_Longitude(String dddmmmmm) {
+		double ddd = Float.parseFloat(dddmmmmm.substring(0, 3));
+		double mins = Float.parseFloat(dddmmmmm.substring(3));
+		return ddd + mins / 60.0;
+	}
+	

and some port numbers that needed to be changed? 

I thought that the entire parser was being rewritten

**Comment by VivaanBahl** [comment]
According to the website linked in the issue it is

**Comment by TrevorDecker** [comment]
awesome,  In that case I am good with this patch.  


If you have time could you remove the dead code and make the port assignments strings into static finals.  If not we can get it in another patch

**Comment by VivaanBahl** [comment]
sure I'll do that right now

**Comment by TrevorDecker** [comment]
Did you mean to close this without merging it into master?

**Comment by VivaanBahl** [comment]
yeah I closed it because this branch was based off the vasu_location_fix branch

**Comment by TrevorDecker** [comment]
Already in master so I am going to close this

**Pull request closed without merging**
