### PR TITLE
Bypass the steering center

### PR DESCRIPTION
**Pull request by grypoB**
Due to mechanical failure, we had to bypass the steering center function at boot of the Arduino.
This is the code that run on low level during raceday

### CODE REVIEW

**Comment by VivaanBahl** [comment]
I'll try and address this by EOD today

**Comment by VivaanBahl** [comment]
@ramensandwich has volunteered to look this over

**Comment by ramensandwich** [comment]
As per the github checks, this will need to be updated with the latest code from master first

**Comment by ramensandwich** [comment]
Are we fine with merging this in before we establish a long-term plan for how we'll handle steering centering on Transistor?  I'd like to discuss this briefly with the team before merging.  That being said, I'm not entirely against merging this in

**Comment by ramensandwich** [comment]
I'm gonna close this because merging this in means we have dead code in the repository.

**Pull request closed without merging**
