### PR TITLE
Kbrennan

### PR DESCRIPTION
**Pull request by TrevorDecker**

### CODE REVIEW

**Comment by ihartwig** [comment]
This pull looks odd. Wasn't a lot of this code already in master? I'm pretty sure that Trevor isn't the original author of some of these commits (like 42d7194). What happened?

**Comment by ihartwig** [comment]
Do not merge until you explain commit 2bf068694af1469895a957a619e1be7f9d1aa339 .

**Comment by msebek** [comment]
Ian is correct. Consider the following pull request by @ramensandwich (https://github.com/CMU-Robotics-Club/RoboBuggy/pull/135) with the commit ID 672c66d. 

This commit is seen again above. This means that there are still aftershocks of "April-ish 2015 Push -F Massacre". Most commits from master were pulled into other branches. This means that 672c66d was not pulled into my branch before master was slain, but it was pulled into kevins. 

We probably should have everyone with an outstanding branch merge their stuff. This will allow us to recover history that was lost, with fewer merge conflicts sooner rather than later.

**Comment by ihartwig** [comment]
I think 42d7194 is explained by me writing code on Trevor's computer and committing.

I think if there is more lost history at this point it's not really recoverable. It's nice that we got most things back. We should NEVER EVER EVER do that again.

Travis CI should be fixed (since Trevor just said it was "fixed"), and master should be pulled in to this branch to confirm that it will merge cleanly. I'm pretty sure there are conflicts in here.

**Comment by TrevorDecker** [comment]
So the trevor branch will be pushed into master soon.  We can ignore all
other pull requests for now.  I am waiting to commit because all of my code
interfaces are not finished.

I do not remember what this pull request was about but I think all of the
relevance parts are in trevor

Ian is correct. Consider the following pull request by @ramensandwich
<https://github.com/ramensandwich> (#135
<https://github.com/CMU-Robotics-Club/RoboBuggy/pull/135>) with the commit
ID 672c66d
<https://github.com/CMU-Robotics-Club/RoboBuggy/commit/672c66d4826fd3c9e940369458de25754c8622a7>.


This commit is seen again above. This means that there are still
aftershocks of "April-ish 2015 Push -F Massacre". Most commits from master
were pulled into other branches. This means that 672c66d
<https://github.com/CMU-Robotics-Club/RoboBuggy/commit/672c66d4826fd3c9e940369458de25754c8622a7>
was not pulled into my branch before master was slain, but it was pulled
into kevins.

We probably should have everyone with an outstanding branch merge their
stuff. This will allow us to recover history that was lost, with fewer
merge conflicts sooner rather than later.

—
Reply to this email directly or view it on GitHub
<https://github.com/CMU-Robotics-Club/RoboBuggy/pull/138#issuecomment-109400123>
.

**Comment by ihartwig** [comment]
I'm also going to veto merging Trevor for the same reasons.

**Comment by TrevorDecker** [comment]
Decided not to merge into master for reasons stated above.

**Comment by TrevorDecker** [comment]
OK I have been trying to fixup the repo.  I have been trying to rebase the non master branches to be cleaner but our git history is kind of a mess.

It looks like some branches have not been merged into master for 8+ months.  To fix this we have two options.  1) branch a copy of master and just copy the code that we want to keep into that branch.   2) we merge all of the changes that we made into master as several pull requests. 3) just throw away the work that we have done and rebase what we can. 

I think that we should start with option 2 since it keeps some history. For that reason I am reopening this pull request.

**Comment by msebek** [comment]
Why are we rebasing again? What quantifies a git mess?

**Comment by TrevorDecker** [comment]
I am merging master into kbrennan and then going to make a pull request off of that.  We can then cheery pick the merges we want off of that

**Pull request closed without merging**
