### PR TITLE
improved alice style check

### PR DESCRIPTION
**Pull request by TrevorDecker**
will now stop master from having any unwanted prints in it
also sets up the structure for low level to do style checks

### CODE REVIEW

**Comment by TrevorDecker** [comment]
@VivaanBahl can you review and check this

**Comment by VivaanBahl** [comment]
I think this looks good, I'm going to add in a couple of prints back in as RLN notes

**Comment by TrevorDecker** [comment]
whats an RLN note?   I also think that will fail the style check, at least the way I did it

**Comment by VivaanBahl** [comment]
RobobuggyLogicNotification as a note. Basically I want us to put out the status reporting of "starting robot", etc because its a good help to see if the system is starting up correctly

**Comment by TrevorDecker** [comment]
oh ok that makes sense I think it will work

**Comment by VivaanBahl** [comment]
I am signing off on this

**Pull request merged**
