### PR TITLE
I think that I got ordering of which messages to show wrong

### PR DESCRIPTION
**Pull request by TrevorDecker**
I think that I got ordering of which messages to show wrong. 
Can someone verify this.  An exception should always be visible, a warning should only be visible for warning or note, note should only be visible for notes. 

You also may want to create a new message type for Show No Errors, and Debug.  

This entire search could be made more scalable with a list that is traversed for reporting level

### CODE REVIEW

**Comment by VivaanBahl** [comment]
Generally I think the reporting level determines the lower bound of the message to display, not the upper bound, so the booleans should be reversed here

**Comment by VivaanBahl** [comment]
Actually on second look, it seems like it was correct before you made changes. Sorry @TrevorDecker I'm going to close this one :)

**Comment by TrevorDecker** [comment]
@VivaanBahl  I agree the reporting level should determine the lower bound of the level of the message.  Exception is more severe then warning is more sever then note. 

  So if you publish a note it is only seen when you are at reporting level note.  An exception should always be visible, a warning should only be visible for warning or note, note should only be visible for notes.  an exception should always be visible, a warning should only be visible for warning or note, note should only be visible for notes.

look at the way it is currently in master. an exception will only be displayed if RobobuggyConfigFile.REPORTING_LEVEL == EXCEPTION.  I do not think this is correct behavior.

**Comment by VivaanBahl** [comment]
@TrevorDecker OK I see what you were saying, I switched the message and reporting level in my head, that's why I got confused. I'll merge this now

**Pull request merged**
