### PR TITLE
Ihartwig signed rbsm

### PR DESCRIPTION
**Pull request by ihartwig**
Relies on PR #213 .

Tested receiving and sending using the test program built in to rbsm_lib.py:

```
[22:34] [ihartwig@CMU-900976:debugging]% python ./rbsm_lib.py /dev/tty.usbmodem14141
send messages successfully.
here are some messages I'm seeing:
{'status': 'locked', 'data': 200, 'id': 24}
{'status': 'locked', 'data': 100, 'id': 1}
{'status': 'locked', 'data': 1002, 'id': 2}
{'status': 'locked', 'data': 20, 'id': 254}
{'status': 'locked', 'data': -4285, 'id': 20}
{'status': 'locked', 'data': 0, 'id': 255}
{'status': 'unlocked', 'data': 0, 'id': 0}
{'status': 'locked', 'data': 994, 'id': 2}
{'status': 'locked', 'data': -4285, 'id': 20}
{'status': 'locked', 'data': 0, 'id': 255}
{'status': 'locked', 'data': 0, 'id': 21}
{'status': 'locked', 'data': 0, 'id': 22}
{'status': 'locked', 'data': 5896, 'id': 23}
{'status': 'locked', 'data': 200, 'id': 24}
```

### CODE REVIEW

**Comment by ihartwig** [comment]
@jeremyahuang I also converted struct packing to sending messages. Can you double check?

**Comment by TrevorDecker** [comment]
This looks good, has it been tested?

**Comment by jeremyahuang** [comment]
@ihartwig Looks like the send code is correct too. Has it been tested?

**Comment by TrevorDecker** [comment]
I am good for this being merged

**Pull request merged**
