### PR TITLE
Misc. cleanup

### PR DESCRIPTION
**Pull request by ramensandwich**
Mostly minor changes (changing files to have 4 spaces, putting brackets on separate lines, adding comments, etc.), and a few syntactical changes were made to clean up the code base.

### CODE REVIEW

**Comment by TrevorDecker** [comment]
This all looks good to me, have you been able to test it on the buggy? 
once you test it feel free to merge into master

**Comment by jeremyahuang** [comment]
The low level code in 436cc86 and 0706a4c looks fine to me.

**Comment by ramensandwich** [comment]
This has been tested on the buggy and functions as intended.  PR #289 should be merged before this is merged because this PR incorporates its rbsm message receiving code.

**Comment by TrevorDecker** [comment]
This has been accepted

**Pull request merged**
